azs:
- name: z1
  cloud_properties:
    zone: us-central1-a
- name: z2
  cloud_properties:
    zone: us-central1-b
- name: z3
  cloud_properties:
    zone: us-central1-c
- name: z4
  cloud_properties:
    zone: us-central1-f
networks:
- name: private
  type: manual
  subnets:
  - az: z1
    gateway: 10.0.16.1
    range: 10.0.16.0/20
    reserved:
    - 10.0.16.2-10.0.16.3
    - 10.0.31.255
    static:
    - 10.0.31.190-10.0.31.254
    cloud_properties:
      ephemeral_external_ip: true
      network_name: bbl-env-qinghai-2017-02-09t18-53z-network
      subnetwork_name: bbl-env-qinghai-2017-02-09t18-53z-subnet
      tags:
      - bbl-env-qinghai-2017-02-09t18-53z-internal
  - az: z2
    gateway: 10.0.32.1
    range: 10.0.32.0/20
    reserved:
    - 10.0.32.2-10.0.32.3
    - 10.0.47.255
    static:
    - 10.0.47.190-10.0.47.254
    cloud_properties:
      ephemeral_external_ip: true
      network_name: bbl-env-qinghai-2017-02-09t18-53z-network
      subnetwork_name: bbl-env-qinghai-2017-02-09t18-53z-subnet
      tags:
      - bbl-env-qinghai-2017-02-09t18-53z-internal
  - az: z3
    gateway: 10.0.48.1
    range: 10.0.48.0/20
    reserved:
    - 10.0.48.2-10.0.48.3
    - 10.0.63.255
    static:
    - 10.0.63.190-10.0.63.254
    cloud_properties:
      ephemeral_external_ip: true
      network_name: bbl-env-qinghai-2017-02-09t18-53z-network
      subnetwork_name: bbl-env-qinghai-2017-02-09t18-53z-subnet
      tags:
      - bbl-env-qinghai-2017-02-09t18-53z-internal
  - az: z4
    gateway: 10.0.64.1
    range: 10.0.64.0/20
    reserved:
    - 10.0.64.2-10.0.64.3
    - 10.0.79.255
    static:
    - 10.0.79.190-10.0.79.254
    cloud_properties:
      ephemeral_external_ip: true
      network_name: bbl-env-qinghai-2017-02-09t18-53z-network
      subnetwork_name: bbl-env-qinghai-2017-02-09t18-53z-subnet
      tags:
      - bbl-env-qinghai-2017-02-09t18-53z-internal
- name: default
  type: manual
  subnets:
  - az: z1
    gateway: 10.0.16.1
    range: 10.0.16.0/20
    reserved:
    - 10.0.16.2-10.0.16.3
    - 10.0.31.255
    static:
    - 10.0.31.190-10.0.31.254
    cloud_properties:
      ephemeral_external_ip: true
      network_name: bbl-env-qinghai-2017-02-09t18-53z-network
      subnetwork_name: bbl-env-qinghai-2017-02-09t18-53z-subnet
      tags:
      - bbl-env-qinghai-2017-02-09t18-53z-internal
  - az: z2
    gateway: 10.0.32.1
    range: 10.0.32.0/20
    reserved:
    - 10.0.32.2-10.0.32.3
    - 10.0.47.255
    static:
    - 10.0.47.190-10.0.47.254
    cloud_properties:
      ephemeral_external_ip: true
      network_name: bbl-env-qinghai-2017-02-09t18-53z-network
      subnetwork_name: bbl-env-qinghai-2017-02-09t18-53z-subnet
      tags:
      - bbl-env-qinghai-2017-02-09t18-53z-internal
  - az: z3
    gateway: 10.0.48.1
    range: 10.0.48.0/20
    reserved:
    - 10.0.48.2-10.0.48.3
    - 10.0.63.255
    static:
    - 10.0.63.190-10.0.63.254
    cloud_properties:
      ephemeral_external_ip: true
      network_name: bbl-env-qinghai-2017-02-09t18-53z-network
      subnetwork_name: bbl-env-qinghai-2017-02-09t18-53z-subnet
      tags:
      - bbl-env-qinghai-2017-02-09t18-53z-internal
  - az: z4
    gateway: 10.0.64.1
    range: 10.0.64.0/20
    reserved:
    - 10.0.64.2-10.0.64.3
    - 10.0.79.255
    static:
    - 10.0.79.190-10.0.79.254
    cloud_properties:
      ephemeral_external_ip: true
      network_name: bbl-env-qinghai-2017-02-09t18-53z-network
      subnetwork_name: bbl-env-qinghai-2017-02-09t18-53z-subnet
      tags:
      - bbl-env-qinghai-2017-02-09t18-53z-internal
vm_types:
- cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: default
- cloud_properties:
    machine_type: n1-standard-2
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: n1-standard-2
- cloud_properties:
    machine_type: n1-standard-4
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: n1-standard-4
- cloud_properties:
    machine_type: n1-standard-8
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: n1-standard-8
- cloud_properties:
    machine_type: n1-standard-16
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: n1-standard-16
- cloud_properties:
    machine_type: n1-standard-32
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: n1-standard-32
- cloud_properties:
    machine_type: n1-highmem-2
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: n1-highmem-2
- cloud_properties:
    machine_type: n1-highmem-4
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: n1-highmem-4
- cloud_properties:
    machine_type: n1-highmem-8
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: n1-highmem-8
- cloud_properties:
    machine_type: n1-highmem-16
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: n1-highmem-16
- cloud_properties:
    machine_type: n1-highmem-32
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: n1-highmem-32
- cloud_properties:
    machine_type: n1-highcpu-2
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: n1-highcpu-2
- cloud_properties:
    machine_type: n1-highcpu-4
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: n1-highcpu-4
- cloud_properties:
    machine_type: n1-highcpu-8
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: n1-highcpu-8
- cloud_properties:
    machine_type: n1-highcpu-16
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: n1-highcpu-16
- cloud_properties:
    machine_type: n1-highcpu-32
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: n1-highcpu-32
- cloud_properties:
    machine_type: f1-micro
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: f1-micro
- cloud_properties:
    machine_type: g1-small
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: g1-small
- cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: m3.medium
- cloud_properties:
    machine_type: n1-standard-2
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: m3.large
- cloud_properties:
    machine_type: n1-highcpu-2
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: c3.large
- cloud_properties:
    machine_type: n1-highmem-4
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: r3.xlarge
- cloud_properties:
    machine_type: g1-small
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
  name: t2.small
disk_types:
- cloud_properties:
    encrypted: true
    type: pd-ssd
  disk_size: 1024
  name: 1GB
- cloud_properties:
    encrypted: true
    type: pd-ssd
  disk_size: 5120
  name: 5GB
- cloud_properties:
    encrypted: true
    type: pd-ssd
  disk_size: 10240
  name: 10GB
- cloud_properties:
    encrypted: true
    type: pd-ssd
  disk_size: 51200
  name: 50GB
- cloud_properties:
    encrypted: true
    type: pd-ssd
  disk_size: 102400
  name: 100GB
- cloud_properties:
    encrypted: true
    type: pd-ssd
  disk_size: 512000
  name: 500GB
- cloud_properties:
    encrypted: true
    type: pd-ssd
  disk_size: 1048576
  name: 1TB
compilation:
  az: z1
  network: private
  reuse_compilation_vms: true
  vm_extensions:
  - 100GB_ephemeral_disk
  vm_type: n1-highcpu-8
  workers: 6
vm_extensions:
- name: 5GB_ephemeral_disk
  cloud_properties:
    root_disk_size_gb: 5
    root_disk_type: pd-ssd
- name: 10GB_ephemeral_disk
  cloud_properties:
    root_disk_size_gb: 10
    root_disk_type: pd-ssd
- name: 50GB_ephemeral_disk
  cloud_properties:
    root_disk_size_gb: 50
    root_disk_type: pd-ssd
- name: 100GB_ephemeral_disk
  cloud_properties:
    root_disk_size_gb: 100
    root_disk_type: pd-ssd
- name: 500GB_ephemeral_disk
  cloud_properties:
    root_disk_size_gb: 500
    root_disk_type: pd-ssd
- name: 1TB_ephemeral_disk
  cloud_properties:
    root_disk_size_gb: 1000
    root_disk_type: pd-ssd
- name: internet-required
  cloud_properties:
    ephemeral_external_ip: true
- name: internet-not-required
  cloud_properties:
    ephemeral_external_ip: false
