<%
['zone', 'zone2', 'region'].each do |val|
  if ENV[val].nil? || ENV[val].empty?
    raise "Missing environment variable: #{val}"
  end
end
zone_1 = ENV['zone']
zone_2 = ENV['zone2']
region = ENV['region']

concourse_region = ENV['concourse_region']

# Google network settings
google_region_compilation = ENV['region_compilation']
google_zone_compilation = ENV['zone_compilation']

# Network
network = ENV['network']
compilation_subnetwork = ENV['compilation_subnet']
private_subnetwork = ENV['private_subnet']

# Google service account settings
project_id = ENV['project_id']
org, project = project_id.split(":")
project_domain_prefix = [project, org].compact.join(".")
cf_service_account = "cf-component@#{project_domain_prefix}.iam.gserviceaccount.com"
%>

azs:
- name: z1
  cloud_properties:
    zone: <%=zone_1 %>
- name: z2
  cloud_properties:
    zone: <%=zone_2 %>

vm_types:
- name: common
  cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 20
    root_disk_type: pd-ssd

- name: worker
  cloud_properties:
    machine_type: n1-standard-2
    root_disk_size_gb: 100
    root_disk_type: pd-ssd

- name: cf-common
  cloud_properties:
    zone: <%= zone_1 %>
    machine_type: n1-standard-1
    root_disk_size_gb: 20
    root_disk_type: pd-standard
    service_account: <%= cf_service_account %>

- name: gorouter
  cloud_properties:
    zone: <%= zone_1 %>
    machine_type: n1-standard-1
    root_disk_size_gb: 20
    root_disk_type: pd-standard
    target_pool: cf-public
    service_account: <%= cf_service_account %>
    tags:
      - cf-public

- name: cells
  cloud_properties:
    zone: <%= zone_1 %>
    machine_type: n1-standard-1
    root_disk_size_gb: 100
    root_disk_type: pd-standard
    service_account: <%= cf_service_account%>

disk_types:
  - name: database
    disk_size: 10240

  - name: consul-etcd
    disk_size: 2048

  - name: mysql
    disk_size: 10240

  - name: diego
    disk_size: 2048

vm_extensions:
- name: concourse-lb
  cloud_properties:
    target_pool: concourse-target-pool

compilation:
  workers: 4
  network: compilation
  reuse_compilation_vms: true
  cloud_properties:
    zone: <%= google_zone_compilation%>
    region: <%= google_region_compilation%>
    machine_type: n1-standard-2
    root_disk_size_gb: 100
    root_disk_type: pd-ssd
    preemptible: true
    service_account: <%= cf_service_account%>

networks:
  - name: public
    type: manual
    subnets:
    - az: z1
      range: 10.150.0.0/24
      gateway: 10.150.0.1
      cloud_properties:
        network_name: bosh
        subnetwork_name: concourse-public-<%= concourse_region %>-1
        ephemeral_external_ip: true
        tags:
          - concourse-public
          - concourse-internal
    - az: z2
      range: 10.160.0.0/24
      gateway: 10.160.0.1
      cloud_properties:
        network_name: bosh
        subnetwork_name: concourse-public-<%= concourse_region %>-2
        ephemeral_external_ip: true
        tags:
          - concourse-public
          - concourse-internal

  - name: compilation
    type: manual
    subnets:
    - range: 10.200.0.0/16
      gateway: 10.200.0.1
      cloud_properties:
        zone: <%= google_zone_compilation%>
        region: <%= google_region_compilation%>
        network_name: <%= network%>
        subnetwork_name: <%= compilation_subnetwork%>
        ephemeral_external_ip: false
        tags:
          - cf-internal
          - bosh-internal
          - no-ip

  - name: private
    type: manual
    subnets:
    - range: 192.168.0.0/16
      gateway: 192.168.0.1
      cloud_properties:
        zone: <%= zone_1 %>
        network_name: <%= network%>
        subnetwork_name: <%= private_subnetwork%>
        ephemeral_external_ip: false
        tags:
          - cf-internal
          - bosh-internal
          - no-ip

  - name: vip
    type: vip
