azs:
- name: z1
- name: z2

vm_types:
- name: common
- name: worker

compilation:
  workers: 2
  network: public
  reuse_compilation_vms: true
  az: z1
  cloud_properties:
    machine_type: common

networks:
  - name: public
    type: manual
    subnets:
    - range: 10.150.0.0/24
      gateway: 10.150.0.1
      cloud_properties:
        network_name: concourse
        subnetwork_name: concourse-public-<%=region %>-1
        ephemeral_external_ip: true
        tags:
          - concourse-public
          - concourse-internal
    - az: z2
      range: 10.160.0.0/24
      gateway: 10.160.0.1
      cloud_properties:
        network_name: concourse

disk_types:
- name: database
