---

networks:
  - name: articulate
    type: manual
    subnets:
    - range: 10.244.9.0/24
      gateway: 10.244.9.1
      static: [10.244.9.2 - 10.244.9.10]
  - name: redis
    type: manual
    subnets:
    - range: 10.244.1.0/24
      gateway: 10.244.1.1
      static: []
    - range: 10.244.2.0/24
      gateway: 10.244.2.1
      static: [10.244.2.2, 10.244.2.6]
  - name: concourse
    type: manual
    subnets:
    - range: 10.244.8.0/24
      gateway: 10.244.8.1
      static: [10.244.8.2 - 10.244.8.10]

compilation:
  cloud_properties:
    name: random
  network: articulate
  reuse_compilation_vms: true
  workers: 6

resource_pools:
- name: articulate
  cloud_properties:
    name: random
  network: articulate
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
- name: redis
  cloud_properties:
    name: random
  network: redis
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
- name: concourse
  network: concourse
  cloud_properties: {}
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

